import { Poppins } from "next/font/google";
import { ThemeProvider } from 'next-themes'
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins-sans",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable}  antialiased`}
      >
         <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Toaster position="top-center" />

          {children}
         </ThemeProvider>
      </body>
    </html>
  );
}
